;; tax-report-export.clar
;; Feature 9: On-Chain Tax Event Log
;; Automatically logs buy/sell actions generated by the portfolio rebalancer.
;; By storing the timestamps, assets, amounts, and approximate USD value at the time 
;; of the trade, users can easily query their history to generate tax reports 
;; (capital gains/losses) natively from Stacks blockchain data.

;; =========================================================
;; Constants
;; =========================================================

(define-constant err-unauthorized  (err u1700))
(define-constant err-invalid-data  (err u1701))

;; =========================================================
;; Data Models
;; =========================================================

;; A user can have multiple tax events.
;; We use an auto-incrementing non-fungible counter per user to map their events cleanly.
(define-map user-event-counts
    principal
    uint
)

;; The primary ledger of taxable trade events
(define-map tax-events
    { user: principal, event-id: uint }
    {
        action: (string-ascii 4),       ;; "BUY " or "SELL"
        asset: principal,               ;; STX, sBTC, xUSD addresses
        amount: uint,                   ;; Quantity of asset
        price-usd: uint,                ;; Execution price in USD (scaled)
        block-height: uint              ;; Block timestamp approx
    }
)

;; =========================================================
;; Read-Only Functions
;; =========================================================

(define-read-only (get-user-event-count (user principal))
    (default-to u0 (map-get? user-event-counts user))
)

(define-read-only (get-tax-event (user principal) (event-id uint))
    (ok (map-get? tax-events { user: user, event-id: event-id }))
)

;; =========================================================
;; Public Functions
;; =========================================================

;; Logs a single taxable event.
;; In the unified project, ONLY the `auto-portfolio-rebalancer` contract 
;; would be authorized to call this when a DEX swap occurs.
;; For this module, we simulate the hook using `tx-sender`.
(define-public (record-trade-event (user principal) (action (string-ascii 4)) (asset principal) (amount uint) (price-usd uint))
    (let (
        (current-nonce (get-user-event-count user))
        (new-nonce (+ current-nonce u1))
    )
        ;; Simulate authorization: ensuring only the user (or core protocol) writes this.
        ;; (asserts! (is-eq contract-caller .auto-portfolio-rebalancer) err-unauthorized)
        (asserts! (or (is-eq tx-sender user) (is-eq contract-caller tx-sender)) err-unauthorized)
        (asserts! (> amount u0) err-invalid-data)
        
        (map-set tax-events 
            { user: user, event-id: new-nonce }
            {
                action: action,
                asset: asset,
                amount: amount,
                price-usd: price-usd,
                block-height: stacks-block-height
            }
        )
        
        (map-set user-event-counts user new-nonce)
        
        (ok new-nonce)
    )
)
